{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "5e17161f-d313-43aa-bfd4-87308286e1c2",
   "metadata": {},
   "source": [
    "#### Q1. Explain why we have to use the Exception class while creating a Custom Exception."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a329e821-a7be-411d-b417-13bc5df490d0",
   "metadata": {},
   "source": [
    "Python, when creating a custom exception, it is not strictly necessary to use the built-in Exception class (which serves as the base class for all exceptions). You can create custom exceptions by inheriting from any class within the exception hierarchy, depending on your specific requirements. However, using the Exception class as the base for custom exceptions is a common practice and has several advantages:\n",
    "\n",
    "Conventions and Readability: The Exception class is the standard base class for exceptions in Python. By using it as the base class for your custom exception, you adhere to established coding conventions. This makes your code more readable and predictable for other developers who may work with or maintain your code in the future.\n",
    "\n",
    "Consistency: When you inherit from the Exception class, you ensure that your custom exception follows the same exception hierarchy as built-in exceptions. This consistency allows developers to understand your custom exception in the context of Python's broader exception handling system.\n",
    "\n",
    "Exception Handling: Python's exception handling mechanisms, such as try-except blocks, are designed to work with exceptions that inherit from the Exception class. By using this base class, your custom exception can be caught alongside other built-in exceptions in a unified manner, providing more flexibility in error handling.\n",
    "\n",
    "Compatibility: Many Python libraries and frameworks expect custom exceptions to inherit from Exception or one of its subclasses. If your custom exception follows this convention, it will integrate more seamlessly with existing code and libraries, reducing potential compatibility issues.\n",
    "\n",
    "Documentation: Inheriting from Exception or a related class makes it clear that your class is intended to represent an exception. This is useful for documenting your code and conveying your intentions to other developers.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "28a5c488-f901-4dbb-9d37-e05c0d790ef5",
   "metadata": {},
   "source": [
    "#### Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "e9fcd109-19e5-47be-b544-1c226d5f26ec",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception\n",
      "    TypeError\n",
      "        FloatOperation\n",
      "        MultipartConversionError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "        ModuleNotFoundError\n",
      "        ZipImportError\n",
      "    OSError\n",
      "        ConnectionError\n",
      "            BrokenPipeError\n",
      "            ConnectionAbortedError\n",
      "            ConnectionRefusedError\n",
      "            ConnectionResetError\n",
      "                RemoteDisconnected\n",
      "        BlockingIOError\n",
      "        ChildProcessError\n",
      "        FileExistsError\n",
      "        FileNotFoundError\n",
      "        IsADirectoryError\n",
      "        NotADirectoryError\n",
      "        InterruptedError\n",
      "            InterruptedSystemCall\n",
      "        PermissionError\n",
      "        ProcessLookupError\n",
      "        TimeoutError\n",
      "        UnsupportedOperation\n",
      "        itimer_error\n",
      "        herror\n",
      "        gaierror\n",
      "        SSLError\n",
      "            SSLCertVerificationError\n",
      "            SSLZeroReturnError\n",
      "            SSLWantWriteError\n",
      "            SSLWantReadError\n",
      "            SSLSyscallError\n",
      "            SSLEOFError\n",
      "        Error\n",
      "            SameFileError\n",
      "        SpecialFileError\n",
      "        ExecError\n",
      "        ReadError\n",
      "        URLError\n",
      "            HTTPError\n",
      "            ContentTooShortError\n",
      "        BadGzipFile\n",
      "    EOFError\n",
      "        IncompleteReadError\n",
      "    RuntimeError\n",
      "        RecursionError\n",
      "        NotImplementedError\n",
      "            ZMQVersionError\n",
      "            StdinNotImplementedError\n",
      "        _DeadlockError\n",
      "        BrokenBarrierError\n",
      "        BrokenExecutor\n",
      "            BrokenThreadPool\n",
      "        SendfileNotAvailableError\n",
      "        ExtractionError\n",
      "        VariableError\n",
      "    NameError\n",
      "        UnboundLocalError\n",
      "    AttributeError\n",
      "        FrozenInstanceError\n",
      "    SyntaxError\n",
      "        IndentationError\n",
      "            TabError\n",
      "    LookupError\n",
      "        IndexError\n",
      "        KeyError\n",
      "            NoSuchKernel\n",
      "            UnknownBackend\n",
      "        CodecRegistryError\n",
      "    ValueError\n",
      "        UnicodeError\n",
      "            UnicodeEncodeError\n",
      "            UnicodeDecodeError\n",
      "            UnicodeTranslateError\n",
      "        UnsupportedOperation\n",
      "        JSONDecodeError\n",
      "        SSLCertVerificationError\n",
      "        Error\n",
      "        UnsupportedDigestmodError\n",
      "        IllegalMonthError\n",
      "        IllegalWeekdayError\n",
      "        ParserError\n",
      "        ClassNotFound\n",
      "        ClipboardEmpty\n",
      "        MessageDefect\n",
      "            NoBoundaryInMultipartDefect\n",
      "            StartBoundaryNotFoundDefect\n",
      "            CloseBoundaryNotFoundDefect\n",
      "            FirstHeaderLineIsContinuationDefect\n",
      "            MisplacedEnvelopeHeaderDefect\n",
      "            MissingHeaderBodySeparatorDefect\n",
      "            MultipartInvariantViolationDefect\n",
      "            InvalidMultipartContentTransferEncodingDefect\n",
      "            UndecodableBytesDefect\n",
      "            InvalidBase64PaddingDefect\n",
      "            InvalidBase64CharactersDefect\n",
      "            InvalidBase64LengthDefect\n",
      "            HeaderDefect\n",
      "                InvalidHeaderDefect\n",
      "                HeaderMissingRequiredValue\n",
      "                NonPrintableDefect\n",
      "                ObsoleteHeaderDefect\n",
      "                NonASCIILocalPartDefect\n",
      "                InvalidDateDefect\n",
      "        MacroToEdit\n",
      "        InvalidFileException\n",
      "        UnequalIterablesError\n",
      "        InvalidVersion\n",
      "        _InvalidELFFileHeader\n",
      "        InvalidWheelFilename\n",
      "        InvalidSdistFilename\n",
      "        InvalidSpecifier\n",
      "        InvalidMarker\n",
      "        UndefinedComparison\n",
      "        UndefinedEnvironmentName\n",
      "        InvalidRequirement\n",
      "            RequirementParseError\n",
      "        InvalidVersion\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "        FloatingPointError\n",
      "        OverflowError\n",
      "        ZeroDivisionError\n",
      "            DivisionByZero\n",
      "            DivisionUndefined\n",
      "        DecimalException\n",
      "            Clamped\n",
      "            Rounded\n",
      "                Underflow\n",
      "                Overflow\n",
      "            Inexact\n",
      "                Underflow\n",
      "                Overflow\n",
      "            Subnormal\n",
      "                Underflow\n",
      "            DivisionByZero\n",
      "            FloatOperation\n",
      "            InvalidOperation\n",
      "                ConversionSyntax\n",
      "                DivisionImpossible\n",
      "                DivisionUndefined\n",
      "                InvalidContext\n",
      "    SystemError\n",
      "        CodecRegistryError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "        UserWarning\n",
      "            GetPassWarning\n",
      "            FormatterWarning\n",
      "        EncodingWarning\n",
      "        DeprecationWarning\n",
      "            ProvisionalWarning\n",
      "        PendingDeprecationWarning\n",
      "        SyntaxWarning\n",
      "        RuntimeWarning\n",
      "            ProactorSelectorThreadWarning\n",
      "            UnknownTimezoneWarning\n",
      "            PEP440Warning\n",
      "        FutureWarning\n",
      "            ProvisionalCompleterWarning\n",
      "        ImportWarning\n",
      "        UnicodeWarning\n",
      "        BytesWarning\n",
      "        ResourceWarning\n",
      "        DeprecatedTzFormatWarning\n",
      "        PkgResourcesDeprecationWarning\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Verbose\n",
      "    Error\n",
      "    SubprocessError\n",
      "        CalledProcessError\n",
      "        TimeoutExpired\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "        CancelledError\n",
      "        TimeoutError\n",
      "        InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    ZMQBaseError\n",
      "        ZMQError\n",
      "            ContextTerminated\n",
      "            Again\n",
      "            InterruptedSystemCall\n",
      "        ZMQBindError\n",
      "        NotDone\n",
      "    PickleError\n",
      "        PicklingError\n",
      "        UnpicklingError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "        ConfigLoaderError\n",
      "            ArgumentError\n",
      "        ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "        MultipleInstanceError\n",
      "    ApplicationError\n",
      "    error\n",
      "    TimeoutError\n",
      "    error\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Error\n",
      "        NoSectionError\n",
      "        DuplicateSectionError\n",
      "        DuplicateOptionError\n",
      "        NoOptionError\n",
      "        InterpolationError\n",
      "            InterpolationMissingOptionError\n",
      "            InterpolationSyntaxError\n",
      "            InterpolationDepthError\n",
      "        ParsingError\n",
      "            MissingSectionHeaderError\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    ExceptionPexpect\n",
      "        EOF\n",
      "        TIMEOUT\n",
      "    PtyProcessError\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "        TryNext\n",
      "        UsageError\n",
      "        StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "        InvalidAliasError\n",
      "    Error\n",
      "        InterfaceError\n",
      "        DatabaseError\n",
      "            InternalError\n",
      "            OperationalError\n",
      "            ProgrammingError\n",
      "            IntegrityError\n",
      "            DataError\n",
      "            NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "        IndexSizeErr\n",
      "        DomstringSizeErr\n",
      "        HierarchyRequestErr\n",
      "        WrongDocumentErr\n",
      "        InvalidCharacterErr\n",
      "        NoDataAllowedErr\n",
      "        NoModificationAllowedErr\n",
      "        NotFoundErr\n",
      "        NotSupportedErr\n",
      "        InuseAttributeErr\n",
      "        InvalidStateErr\n",
      "        SyntaxErr\n",
      "        InvalidModificationErr\n",
      "        NamespaceErr\n",
      "        InvalidAccessErr\n",
      "        ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "        InternalError\n",
      "        WrongVersion\n",
      "        RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "        MessageParseError\n",
      "            HeaderParseError\n",
      "            BoundaryError\n",
      "        MultipartConversionError\n",
      "        CharsetError\n",
      "    Error\n",
      "    HTTPException\n",
      "        NotConnected\n",
      "        InvalidURL\n",
      "        UnknownProtocol\n",
      "        UnknownTransferEncoding\n",
      "        UnimplementedFileMode\n",
      "        IncompleteRead\n",
      "        ImproperConnectionState\n",
      "            CannotSendRequest\n",
      "            CannotSendHeader\n",
      "            ResponseNotReady\n",
      "        BadStatusLine\n",
      "            RemoteDisconnected\n",
      "        LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "        NoSuchProcess\n",
      "            ZombieProcess\n",
      "        AccessDenied\n",
      "        TimeoutExpired\n",
      "    _Ipv6UnsupportedError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "        ProtocolError\n",
      "        ResponseError\n",
      "        Fault\n",
      "    ParseBaseException\n",
      "        ParseException\n",
      "        ParseFatalException\n",
      "            ParseSyntaxException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "        VersionConflict\n",
      "            ContextualVersionConflict\n",
      "        DistributionNotFound\n",
      "        UnknownExtra\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, level=0):\n",
    "    print(\"    \" * level + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, level + 1)\n",
    "\n",
    "print_exception_hierarchy(Exception)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0127aee2-d1f3-48bc-9e0d-00cf05a45d02",
   "metadata": {},
   "source": [
    "#### Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "25dd6403-3237-4c91-b7da-cf39de5832de",
   "metadata": {},
   "source": [
    "The ArithmeticError class is a base class for exceptions that are raised for various arithmetic-related errors in Python. It serves as a parent class for several specific arithmetic exception classes. Two common exceptions that are derived from ArithmeticError and that we can discuss are ZeroDivisionError and OverflowError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a1bd7eb4-8e0e-49b4-967f-47f694eaf9df",
   "metadata": {},
   "source": [
    "ZeroDivisionError:\n",
    "\n",
    "Description: This exception is raised when you attempt to divide a number by zero.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b96de5d0-a5d6-4c12-8379-38f0d8380ede",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "dividend = 10\n",
    "divisor = 0\n",
    "\n",
    "try:\n",
    "    result = dividend / divisor\n",
    "except ZeroDivisionError as e:\n",
    "    print(f\"Error: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0bbf2611-7019-4a00-9d8b-383e35ba9df5",
   "metadata": {},
   "source": [
    "OverflowError:\n",
    "\n",
    "This exception is raised when a numerical operation exceeds the limit of what can be represented by the data type (e.g., exceeding the maximum value for an integer)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "b53bd3dd-9514-4aa8-89e9-68d92914e575",
   "metadata": {},
   "outputs": [],
   "source": [
    "import math"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "dd14a8d0-6b77-4043-94aa-fabed796cf23",
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "\n",
    "try:\n",
    "    large_number = math.factorial(1000)\n",
    "except OverflowError as e:\n",
    "    print(f\"Error: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c05d058f-477f-4bea-bedb-e41496b63dd1",
   "metadata": {},
   "source": [
    "#### Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3c9b80ad-5d05-4e99-b961-b66df03afb7d",
   "metadata": {},
   "source": [
    "The LookupError class is a base class for exceptions related to lookup operations, typically when accessing elements in a sequence or mapping (such as a list or dictionary) goes wrong. It serves as a parent class for several specific lookup-related exception classes, including KeyError and IndexError."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "e23a6b61-6a56-4764-b2b7-84639c346d3d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: 'city'\n"
     ]
    }
   ],
   "source": [
    "#KeyError:\n",
    "  #KeyError is raised when you try to access a dictionary key that doesn't exist.\n",
    "    \n",
    "my_dict = {\"name\": \"Alice\", \"age\": 30}\n",
    "try:\n",
    "    print(my_dict[\"city\"])\n",
    "except KeyError as e:\n",
    "    print(f\"Error: {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "413ee8a3-53d4-490b-821b-ca463cdab057",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: list index out of range\n"
     ]
    }
   ],
   "source": [
    "#IndexError:\n",
    "    #IndexError is raised when you try to access an index in a sequence (e.g., a list) that is out of range.\n",
    "    \n",
    "my_list = [1, 2, 3]\n",
    "try:\n",
    "    print(my_list[5])\n",
    "except IndexError as e:\n",
    "    print(f\"Error: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f7ea87fa-4059-42ed-948f-2a09b9e6ab84",
   "metadata": {},
   "source": [
    "Both KeyError and IndexError are specific subclasses of LookupError. They are useful for handling cases where you want to catch lookup-related errors specifically, allowing you to provide appropriate error handling or fallback behavior when trying to access keys in dictionaries or indices in sequences."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bdc584fd-afe0-43c6-9878-a7f5114d3cbb",
   "metadata": {},
   "source": [
    "#### Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6564c881-ec5c-4323-930b-11a60d0cb910",
   "metadata": {},
   "source": [
    "ImportError and ModuleNotFoundError are both exceptions in Python that are related to issues with importing modules. However, there are differences between them\n",
    "\n",
    "ImportError:\n",
    "            ImportError is a general exception that is raised when there is a problem with importing a module, but the specific issue is not further categorized. It can occur for various reasons, such as if the module you are trying to import does not exist, has a syntax error, or encounters an error while executing its code during import."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "8ce0a047-b2f0-4599-92d1-31c53d3abc2c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error importing module: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError as e:\n",
    "    print(f\"Error importing module: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4650c2fc-e66c-43f9-b598-a4b2a50ee2ce",
   "metadata": {},
   "source": [
    "ModuleNotFoundError:\n",
    "      It is raised when Python cannot find the specified module during import. This provides a clearer and more precise error message compared to the more general ImportError."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "0b14b474-c973-4ca0-b2f7-621cdf83bb0d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error importing module: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError as e:\n",
    "    print(f\"Error importing module: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "16b77899-32ca-4553-a76d-ab4497d80374",
   "metadata": {},
   "source": [
    "#### Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c5e82927-3f98-4c62-9ff1-03c2fed56a93",
   "metadata": {},
   "source": [
    "Exception handling is an essential aspect of writing robust and maintainable Python code. Here are some best practices for effective exception handling in Python:\n",
    "\n",
    "Use Specific Exceptions: Whenever possible, catch specific exceptions rather than using a broad except clause. This helps you handle different error scenarios appropriately. For example, use except ValueError instead of just except Exception.\n",
    "\n",
    "Avoid Bare except: Avoid using a bare except clause (i.e., without specifying an exception type) because it can catch unexpected exceptions and make debugging challenging. Be explicit about which exceptions you intend to catch.\n",
    "\n",
    "Use finally Blocks: When necessary, use finally blocks to ensure that certain code, like cleanup operations (closing files or network connections), gets executed regardless of whether an exception was raised or not.\n",
    "\n",
    "Keep try Blocks Minimal: Keep the code inside your try block minimal. Only include code that might raise exceptions. This helps narrow down the scope of potential errors and makes your code more readable.\n",
    "\n",
    "Handle Exceptions Where They Occur: Handle exceptions as close as possible to where they occur. This makes it easier to pinpoint the source of the problem and helps maintain code readability.\n",
    "\n",
    "Don't Suppress Exceptions: Avoid suppressing exceptions without proper handling. If you catch an exception but don't handle it or log it, it can lead to hidden bugs and issues.\n",
    "\n",
    "Use Multiple except Blocks: Use multiple except blocks to handle different exception types separately. This allows you to provide specific error messages or actions for each type of exception.\n",
    "\n",
    "Logging: Consider using a logging framework (e.g., Python's logging module) to log exceptions and error messages. Logging can be invaluable for debugging and troubleshooting.\n",
    "\n",
    "Raising Exceptions: Raise exceptions when appropriate. If your code encounters a situation that should be considered an error, raise a relevant exception with a clear error message to signal the issue to calling code.\n",
    "\n",
    "Custom Exceptions: When designing your own functions or classes, consider defining custom exception classes that inherit from built-in exceptions. This allows you to create more meaningful and specific error messages for your application.\n",
    "\n",
    "Graceful Degradation: When handling exceptions, aim for graceful degradation. Try to provide fallback behavior or error messages that allow your program to continue running or fail gracefully rather than crashing.\n",
    "\n",
    "Use with Statements: For resource management (e.g., opening files or database connections), use with statements and context managers. They ensure proper cleanup even if exceptions are raised.\n",
    "\n",
    "Documentation: Document the exceptions that your functions or methods can raise. Include this information in docstrings or comments to help other developers understand how to handle your code correctly.\n",
    "\n",
    "Testing: Write unit tests that cover exception scenarios. Ensure that your code behaves as expected when exceptions are raised and caught.\n",
    "\n",
    "Avoid Silencing Exceptions: Be cautious when using constructs like pass or continue inside exception handlers. They can mask issues and lead to subtle bugs. If you don't handle an exception, consider at least logging it."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "65694921-eba0-4c99-acd3-5f94a6755347",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
